import { MigrationInterface, QueryRunner } from "typeorm";

export class PopoFixSnakeCase8151755261347582 implements MigrationInterface {
    name = 'PopoFixSnakeCase8151755261347582'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`nickname\` DROP FOREIGN KEY \`FK_6406e4d246bfcc6199420952541\``);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` DROP FOREIGN KEY \`FK_dea9472e4a513d65e387f225d6c\``);
        await queryRunner.query(`DROP INDEX \`IDX_6406e4d246bfcc619942095254\` ON \`nickname\``);
        await queryRunner.query(`DROP INDEX \`REL_6406e4d246bfcc619942095254\` ON \`nickname\``);
        await queryRunner.query(`DROP INDEX \`IDX_0a5b7966f6ab9aaae768ce4636\` ON \`fcm_key\``);
        await queryRunner.query(`ALTER TABLE \`whitebook\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`whitebook\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`updateAt\``);
        await queryRunner.query(`ALTER TABLE \`nickname\` DROP COLUMN \`user_uuid\``);
        await queryRunner.query(`ALTER TABLE \`nickname\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`nickname\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` DROP COLUMN \`user_uuid\``);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` DROP COLUMN \`push_key\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`user_type\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`last_login_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`crypto_salt\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`user_status\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`hashed_refresh_token\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`refresh_token_expires_at\``);
        await queryRunner.query(`ALTER TABLE \`notice\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`notice\` DROP COLUMN \`updateAt\``);
        await queryRunner.query(`ALTER TABLE \`equip\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`equip\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`discount\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`discount\` DROP COLUMN \`updateAt\``);
        await queryRunner.query(`ALTER TABLE \`intro_club\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`intro_club\` DROP COLUMN \`updateAt\``);
        await queryRunner.query(`ALTER TABLE \`intro_association\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`intro_association\` DROP COLUMN \`updateAt\``);
        await queryRunner.query(`ALTER TABLE \`whitebook\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`whitebook\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reserve_equip\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nickname\` ADD \`userUuid\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`nickname\` ADD UNIQUE INDEX \`IDX_30b488b4298d857c45e04e6ec5\` (\`userUuid\`)`);
        await queryRunner.query(`ALTER TABLE \`nickname\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nickname\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` ADD \`userUuid\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` ADD \`pushKey\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` ADD UNIQUE INDEX \`IDX_6e9c98fcda8bae19d7939a59f4\` (\`pushKey\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`cryptoSalt\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`userType\` varchar(255) NOT NULL DEFAULT 'STUDENT'`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`userStatus\` varchar(255) NOT NULL DEFAULT 'DEACTIVATED'`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`hashedRefreshToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`refreshTokenExpiresAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`lastLoginAt\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notice\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notice\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`equip\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`equip\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`favorite_place\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`discount\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`discount\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`whitebook\` CHANGE \`content\` \`content\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reserve_equip\` DROP FOREIGN KEY \`FK_1a21707561c620b45da2dc7e490\``);
        await queryRunner.query(`ALTER TABLE \`reserve_equip\` CHANGE \`booker_id\` \`booker_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reserve_equip\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`location\` \`location\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`staff_email\` \`staff_email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` DROP FOREIGN KEY \`FK_ccafe6dd7a565b48b180aaa89d0\``);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` DROP FOREIGN KEY \`FK_c8a3a7bb2076a4a2105d3573612\``);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` CHANGE \`place_id\` \`place_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` CHANGE \`booker_id\` \`booker_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notice\` CHANGE \`content\` \`content\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notice\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notice\` CHANGE \`link\` \`link\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`equip\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`equip\` CHANGE \`staff_email\` \`staff_email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`equip\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`calendar\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`discount\` CHANGE \`region\` \`region\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`discount\` CHANGE \`open_hour\` \`open_hour\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`discount\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`content\` \`content\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`homepage_url\` \`homepage_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`facebook_url\` \`facebook_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`instagram_url\` \`instagram_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`youtube_url\` \`youtube_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` CHANGE \`content\` \`content\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` CHANGE \`homepage_url\` \`homepage_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` CHANGE \`facebook_url\` \`facebook_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` CHANGE \`instagram_url\` \`instagram_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`affiliate\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`affiliate\` CHANGE \`content_short\` \`content_short\` text NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_30b488b4298d857c45e04e6ec5\` ON \`nickname\` (\`userUuid\`)`);
        await queryRunner.query(`ALTER TABLE \`reserve_equip\` ADD CONSTRAINT \`FK_1a21707561c620b45da2dc7e490\` FOREIGN KEY (\`booker_id\`) REFERENCES \`user\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` ADD CONSTRAINT \`FK_ccafe6dd7a565b48b180aaa89d0\` FOREIGN KEY (\`place_id\`) REFERENCES \`place\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` ADD CONSTRAINT \`FK_c8a3a7bb2076a4a2105d3573612\` FOREIGN KEY (\`booker_id\`) REFERENCES \`user\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`nickname\` ADD CONSTRAINT \`FK_30b488b4298d857c45e04e6ec52\` FOREIGN KEY (\`userUuid\`) REFERENCES \`user\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` ADD CONSTRAINT \`FK_0a9a65f3c7649c91ca60aedf536\` FOREIGN KEY (\`userUuid\`) REFERENCES \`user\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`fcm_key\` DROP FOREIGN KEY \`FK_0a9a65f3c7649c91ca60aedf536\``);
        await queryRunner.query(`ALTER TABLE \`nickname\` DROP FOREIGN KEY \`FK_30b488b4298d857c45e04e6ec52\``);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` DROP FOREIGN KEY \`FK_c8a3a7bb2076a4a2105d3573612\``);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` DROP FOREIGN KEY \`FK_ccafe6dd7a565b48b180aaa89d0\``);
        await queryRunner.query(`ALTER TABLE \`reserve_equip\` DROP FOREIGN KEY \`FK_1a21707561c620b45da2dc7e490\``);
        await queryRunner.query(`DROP INDEX \`REL_30b488b4298d857c45e04e6ec5\` ON \`nickname\``);
        await queryRunner.query(`ALTER TABLE \`affiliate\` CHANGE \`content_short\` \`content_short\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`affiliate\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` CHANGE \`instagram_url\` \`instagram_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` CHANGE \`facebook_url\` \`facebook_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` CHANGE \`homepage_url\` \`homepage_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` CHANGE \`content\` \`content\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`youtube_url\` \`youtube_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`instagram_url\` \`instagram_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`facebook_url\` \`facebook_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`homepage_url\` \`homepage_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` CHANGE \`content\` \`content\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`discount\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`discount\` CHANGE \`open_hour\` \`open_hour\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`discount\` CHANGE \`region\` \`region\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`calendar\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`equip\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`equip\` CHANGE \`staff_email\` \`staff_email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`equip\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notice\` CHANGE \`link\` \`link\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notice\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notice\` CHANGE \`content\` \`content\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` CHANGE \`booker_id\` \`booker_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` CHANGE \`place_id\` \`place_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` ADD CONSTRAINT \`FK_c8a3a7bb2076a4a2105d3573612\` FOREIGN KEY (\`booker_id\`) REFERENCES \`user\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` ADD CONSTRAINT \`FK_ccafe6dd7a565b48b180aaa89d0\` FOREIGN KEY (\`place_id\`) REFERENCES \`place\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`image_url\` \`image_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`staff_email\` \`staff_email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`location\` \`location\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reserve_equip\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reserve_equip\` CHANGE \`booker_id\` \`booker_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reserve_equip\` ADD CONSTRAINT \`FK_1a21707561c620b45da2dc7e490\` FOREIGN KEY (\`booker_id\`) REFERENCES \`user\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`whitebook\` CHANGE \`content\` \`content\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`intro_association\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`intro_club\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`intro_club\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`discount\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`discount\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`favorite_place\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`equip\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`equip\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`notice\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`notice\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`lastLoginAt\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`refreshTokenExpiresAt\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`hashedRefreshToken\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`userStatus\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`userType\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`cryptoSalt\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` DROP INDEX \`IDX_6e9c98fcda8bae19d7939a59f4\``);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` DROP COLUMN \`pushKey\``);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` DROP COLUMN \`userUuid\``);
        await queryRunner.query(`ALTER TABLE \`nickname\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`nickname\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`nickname\` DROP INDEX \`IDX_30b488b4298d857c45e04e6ec5\``);
        await queryRunner.query(`ALTER TABLE \`nickname\` DROP COLUMN \`userUuid\``);
        await queryRunner.query(`ALTER TABLE \`reserve_place\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`reserve_equip\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`whitebook\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`whitebook\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`intro_association\` ADD \`updateAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`intro_association\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` ADD \`updateAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`intro_club\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`discount\` ADD \`updateAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`discount\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`equip\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`equip\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notice\` ADD \`updateAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notice\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`refresh_token_expires_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`hashed_refresh_token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`user_status\` varchar(255) NOT NULL DEFAULT ''DEACTIVATED''`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`crypto_salt\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`last_login_at\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`user_type\` varchar(255) NOT NULL DEFAULT ''STUDENT''`);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` ADD \`push_key\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` ADD \`user_uuid\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`nickname\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nickname\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nickname\` ADD \`user_uuid\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`updateAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`whitebook\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`whitebook\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_0a5b7966f6ab9aaae768ce4636\` ON \`fcm_key\` (\`push_key\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_6406e4d246bfcc619942095254\` ON \`nickname\` (\`user_uuid\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_6406e4d246bfcc619942095254\` ON \`nickname\` (\`user_uuid\`)`);
        await queryRunner.query(`ALTER TABLE \`fcm_key\` ADD CONSTRAINT \`FK_dea9472e4a513d65e387f225d6c\` FOREIGN KEY (\`user_uuid\`) REFERENCES \`user\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`nickname\` ADD CONSTRAINT \`FK_6406e4d246bfcc6199420952541\` FOREIGN KEY (\`user_uuid\`) REFERENCES \`user\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
